### ISSUE TITLE
Installed putio-automator on linux subsystem error on putio torrents add

### ISSUE THREAD

**Issue by krash1220** [datashaman/putio-automator#28]
I just installed this on Windows 10 subsystem last week and it was working just fine. Today I was doing a clean install and now I get this error when I try to add or watch torrents.
krash@Karens-HP-Laptop:~$ putio torrents add
Traceback (most recent call last):
  File "/home/krash/.local/bin/putio", line 11, in <module>
    sys.exit(main())
  File "/home/krash/.local/lib/python2.7/site-packages/putio_automator/manage.py", line 47, in main
    manager.run()
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/krash/.local/lib/python2.7/site-packages/putio_automator/commands/torrents.py", line 52, in add
    with_db(app, func)
  File "/home/krash/.local/lib/python2.7/site-packages/putio_automator/db.py", line 15, in with_db
    func(connection)
  File "/home/krash/.local/lib/python2.7/site-packages/putio_automator/commands/torrents.py", line 29, in func
    conn.execute("select datetime(created_at, 'localtime') from torrents where name = ? and size = ?", (name, size))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by datashaman** [comment]
Argh, this will probably go away if I upgrade to python3. I'll have a look, thanks for the report. Perhaps you can get around this by renaming one of the torrent files.

**Comment by datashaman** [comment]
#34 uses python 3. please see if this is still an issue.
