### ISSUE TITLE
Issue with putio config init

### ISSUE THREAD

**Issue by ZerithZA** [datashaman/putio-automator#36]
Hi,

I did a new install on two different Ubuntu 18.04.5 LTS boxes and on both I get the following error when running the putio config init command.

Traceback (most recent call last):
  File "/home/zerith/.local/bin/putio", line 5, in <module>
    from putio_automator.cli import main
  File "/home/zerith/.local/lib/python3.6/site-packages/putio_automator/cli.py", line 34, in <module>
    from . import commands
  File "/home/zerith/.local/lib/python3.6/site-packages/putio_automator/commands/__init__.py", line 8, in <module>
    import putio_automator.commands.torrents
  File "/home/zerith/.local/lib/python3.6/site-packages/putio_automator/commands/torrents.py", line 12, in <module>
    from fswatch import Monitor
  File "/home/zerith/.local/lib/python3.6/site-packages/fswatch/__init__.py", line 2, in <module>
    from .fswatch import Monitor
  File "/home/zerith/.local/lib/python3.6/site-packages/fswatch/fswatch.py", line 4, in <module>
    from fswatch import libfswatch
  File "/home/zerith/.local/lib/python3.6/site-packages/fswatch/libfswatch.py", line 9, in <module>
    fsw_init_library = lib.fsw_init_library
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: fsw_init_library

Any idea why this will happen?

**Comment by ZerithZA** [comment]
I've also tried to install under Python 2.7 but cannot find fswatch.

~$ pip2.7 install --user putio-automator
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting putio-automator
  Using cached putio-automator-2.0.0.tar.gz (12 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting click-log
  Using cached click_log-0.3.2-py2.py3-none-any.whl (4.6 kB)
ERROR: Could not find a version that satisfies the requirement fswatch (from putio-automator) (from versions: none)
ERROR: No matching distribution found for fswatch (from putio-automator)
WARNING: You are using pip version 20.3.4; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.

**Comment by datashaman** [comment]
I'll need to rethink this choice - it looks like you need an OS package in addition to the python one. Try `apt install fswatch`, then try again. If that works, awesome. I will look for an alternative solution that doesn't require an OS package to support it. 🤞🏼

**Comment by ZerithZA** [comment]
Hi, I initially did manually try to install both fs-watch and fswatch to see if either worked but neither did. I also tried via apt and made no difference. 

```
nuc:/mnt/files/downloads/putio$ sudo apt install fswatch
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libfswatch9
The following NEW packages will be installed:
  fswatch libfswatch9
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 166 kB of archives.
After this operation, 526 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://za.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libfswatch9 amd64 1.11.2+repack-10ubuntu0.1 [93.7 kB]
Get:2 http://za.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 fswatch amd64 1.11.2+repack-10ubuntu0.1 [72.0 kB]
Fetched 166 kB in 1s (280 kB/s)
Selecting previously unselected package libfswatch9.
(Reading database ... 188863 files and directories currently installed.)
Preparing to unpack .../libfswatch9_1.11.2+repack-10ubuntu0.1_amd64.deb ...
Unpacking libfswatch9 (1.11.2+repack-10ubuntu0.1) ...
Selecting previously unselected package fswatch.
Preparing to unpack .../fswatch_1.11.2+repack-10ubuntu0.1_amd64.deb ...
Unpacking fswatch (1.11.2+repack-10ubuntu0.1) ...
Setting up libfswatch9 (1.11.2+repack-10ubuntu0.1) ...
Setting up fswatch (1.11.2+repack-10ubuntu0.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
nuc:/mnt/files/downloads/putio$ pip2.7 install --user putio-automator
/usr/lib/python2.7/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.utils import int_from_bytes
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting putio-automator
  Using cached putio-automator-2.0.0.tar.gz (12 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from putio-automator) (7.1.2)
Collecting click-log
  Using cached click_log-0.3.2-py2.py3-none-any.whl (4.6 kB)
ERROR: Could not find a version that satisfies the requirement fswatch (from putio-automator) (from versions: none)
ERROR: No matching distribution found for fswatch (from putio-automator)
```

**Comment by ZerithZA** [comment]
I tried with pip 21.2.4 (python 3.6) and get the following.

`@nuc:~$ putio config init
Traceback (most recent call last):
  File "/home/**/.local/bin/putio", line 5, in <module>
    from putio_automator.cli import main
  File "/home/**/.local/lib/python3.6/site-packages/putio_automator/cli.py", line 34, in <module>
    from . import commands
  File "/home/**/.local/lib/python3.6/site-packages/putio_automator/commands/__init__.py", line 8, in <module>
    import putio_automator.commands.torrents
  File "/home/**/.local/lib/python3.6/site-packages/putio_automator/commands/torrents.py", line 12, in <module>
    from fswatch import Monitor
  File "/home/**/.local/lib/python3.6/site-packages/fswatch/__init__.py", line 2, in <module>
    from .fswatch import Monitor
  File "/home/**/.local/lib/python3.6/site-packages/fswatch/fswatch.py", line 4, in <module>
    from fswatch import libfswatch
  File "/home/**/.local/lib/python3.6/site-packages/fswatch/libfswatch.py", line 9, in <module>
    fsw_init_library = lib.fsw_init_library
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: fsw_init_library
`

**Comment by datashaman** [comment]
can you try this with the more recent LTS?

**Comment by datashaman** [comment]
I'll have a hotfix out by the end of the day for this. I'll use some ducktyping and mix the two approaches depending on OS.

**Comment by ZerithZA** [comment]
Awesome, thanks.

**Comment by datashaman** [comment]
yes, you must use `--user` option when installing.

**Comment by datashaman** [comment]
find which config file is being used with:
```
putio config show
```
then verify the contents of the file are correct.

if you are always executing this from a specific folder, you can override the config with a .env file with the appropriate values in it.

**Comment by datashaman** [comment]
use `which putio` to figure out which binary you are executing. it should be in `~/.local/bin` for ubuntu i think.
