### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by mtauberjr** [datashaman/putio-automator#42]
putio config init
Traceback (most recent call last):
  File "/home/mtauberjr/.local/bin/putio", line 5, in <module>
    from putio_automator.cli import main
  File "/home/mtauberjr/.local/lib/python3.9/site-packages/putio_automator/cli.py", line 16, in <module>
    config = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 562, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'

**Comment by datashaman** [comment]
I've duplicated this in a docker container. On it.
